language: python
cache: pip
sudo: false
matrix:
  include:
  - env: TOXENV=py34-django18
    python: 3.6
  - env: TOXENV=py34-django19
    python: 3.6
  - env: TOXENV=py34-django110
    python: 3.6
  - env: TOXENV=py35-django110
    python: 3.6
  - env: TOXENV=py35-django111
    python: 3.6
  - env: TOXENV=py35-django20
    python: 3.6
install:
  - pip install tox
script:
- tox
